### ISSUE TITLE
找不到`FFTW`库的dll和gsl库的ddl文件

### ISSUE THREAD

**Issue by Prines** [czyt1988/sa#11]
按照您的build.md文件进行构建，到了程序异常那一步，但我却找不到您的解决方法里说得ddl文件

**Comment by czyt1988** [comment]
是已经构建完成了吗，构建完成程序自动运行会报异常，主要是缺乏dll
dll是在sa\src\3rdParty\gsl\gsl.dll.7z的压缩包里，以及sa\src\3rdParty\fftw\fftw32\libfftw3-3.dll.7z里，解压即可
还需要构建目录的lib文件下生成的dll文件

**Comment by Prines** [comment]
您好，我重新下载您的项目按照您的build.md文件进行构建
1.先构建qwt成功​
2.然后拉取SARibbon
3.直接构建sa.pro，失败，失败提示如下，请问这是什么原因了（我第一次构建时SARibbon.pro位置在sa-master\src\SARibbonBar\SARibbon，我以为是这个路径错了，然后我把那个pro复制到了sa-master\src\SARibbonBar重新构建仍然报错），请问是我做错了那一步吗





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"czy"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月2日(星期四) 中午1:15
收件人:&nbsp;"czyt1988/sa"<sa@noreply.github.com&gt;;
抄送:&nbsp;"武汉理工大学-杨义"<1374569149@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [czyt1988/sa] 找不到`FFTW`库的dll和gsl库的ddl文件 (#11)





 
是已经构建完成了吗，构建完成程序自动运行会报异常，主要是缺乏dll
 dll是在sa\src\3rdParty\gsl\gsl.dll.7z的压缩包里，以及sa\src\3rdParty\fftw\fftw32\libfftw3-3.dll.7z里，解压即可
 还需要构建目录的lib文件下生成的dll文件

**Comment by czyt1988** [comment]
失败提示是啥，SARibbon直接运行updateSARibbon.sh拉取，不需要动其他

**Comment by Prines** [comment]
你好，我上面的邮件里有截图啊，那个截图就是错误提示，我也没有动其他的，直接编译sa.pro


 
---原始邮件---
发件人: "czy"<notifications@github.com&gt;
发送时间: 2020年7月2日(星期四) 晚上6:40
收件人: "czyt1988/sa"<sa@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"Prines"<1374569149@qq.com&gt;;
主题: Re: [czyt1988/sa] 找不到`FFTW`库的dll和gsl库的ddl文件 (#11)




 
失败提示是啥，SARibbon直接运行updateSARibbon.sh拉取，不需要动其他
